### ISSUE TITLE
E432: Tags file not sorted

### ISSUE THREAD

**Issue by ninjacn** [alvan/vim-php-manual#10]
报错信息
E432: Tags file not sorted: /usr/local/share/vim/vim81/doc/tags
操作系统：macos 10.15

为什么会报这个错误呢，有办法屏蔽吗？

**Comment by alvan** [comment]
@ninjacn 
删除你这个tags文件并重新生成排序版本的就可以。
你可以尝试在terminal运行：
`vim +%sort +wq /usr/local/share/vim/vim81/doc/tags`

**Comment by ninjacn** [comment]
> @ninjacn
> 删除你这个tags文件并重新生成排序版本的就可以。
> 你可以尝试在terminal运行：
> `vim +%sort +wq /usr/local/share/vim/vim81/doc/tags`
> 如果需要权限请使用sudo.

非常感谢回答。我改了下配置解决了。 `set notagbsearch`
