### ISSUE TITLE
Shift-k over a function on "See Also" doesn't work

### ISSUE THREAD

**Issue by molocco** [alvan/vim-php-manual#2]
Lets say I open the manual for trim, then I scroll to the bottom and I find:

See Also:
* ltrim
* rtrim
etc..

It would be good to be able to navigate somehow to those man pages (ie: using shift-k over any of those functions).
Right now I get: 
No manual entry for "name of the function"
shell returned 16

**Comment by alvan** [comment]
Hi, @molocco 
I recommend you simply use the shortcut key "C+]" to jump to a tag when you are in manual pages,
you can type `:h tags` to see more details about vim tags.

**Comment by molocco** [comment]
ok, thanks!
