### ISSUE TITLE
pman required? docs sometimes shown in vim window, sometimes manpage style

### ISSUE THREAD

**Issue by tolry** [alvan/vim-php-manual#7]
Hi,

first of all, thanks for this great plugin, have been using it for years. But there lies the problem, it has been some time, since I installed and trying to get it running on a new machine was harder than I thought.

1. is 'pman' a hard requirement? I was getting an error message before and installed via this composer package (and docker) https://github.com/willdurand/pman
2. I have the exact same vim-configuration (https://github.com/tolry/vim) running on at least three machines and one of them shows the docs in a new vim-window, the others switch to the 'shell' and display a b/w manpage - all have w3m installed - any ideas?

Thanks in advance,
Tobias

**Comment by alvan** [comment]
@tolry 
The plugin itself has no required dependencies.
You can check the `Install options` part.
The easiest way to install this plugin is to put it in the vim runtime path, then it will work.

**Comment by tolry** [comment]
@alvan thanks for your response. I am using vim-plug for all vim plugins having the above mentioned problems, I will try figuring out what's going wrong here an report back :smile:
